### ISSUE TITLE
Incorrect predicted depth of closest in path objects

### ISSUE THREAD

**Issue by akashchavan15** [TRI-ML/vidar#33]
I have used monocular depth estimation for my own data. I see that the depths for closest-in-path objects are not correct. Can someone help me to fix this? 

Please find the attached images for more details. 

![Incorrect_depth](https://user-images.githubusercontent.com/46254831/220709147-27c60c9c-53dd-40d5-9c00-208ff806969d.png)
![Incorrect_depth_1](https://user-images.githubusercontent.com/46254831/220709171-c3ad34f2-3050-48d6-ab0e-3fd440812332.png)

**Comment by akashchavan15** [comment]
can anyone please provide some suggestions?

**Comment by akashchavan15** [comment]
@RaresAmbrus Could you please provide some suggestions?

**Comment by ivasiljevic** [comment]
The photometric loss makes a static scene assumption; if we train on enough data in practice we get models that can predict reasonable depth on dynamic objects (e.g. by generalizing from parked cars to cars in front of the ego-vehicle).  If your dataset is on the smaller side, you're going to get missing depth like that because the dynamic object is masked out.

**Comment by akashchavan15** [comment]
@ivasiljevic Thank you for your reply. I have 60000 images in my training data. What is the best practice I can follow to filter out dynamic scenes from my dataset? I removed static frames.
